CC=gcc
SRCS=\
	Ejemplo1.c\
	Ejemplo2.c\
	Ejemplo3.c

EXES=\
	Ejemplo1\
	Ejemplo2\
	Ejemplo3\
	Ejemplo4\
	Ejemplo5\
	Ejemplo6\
	Ejemplo7\
	Ejemplo8\
	Ejemplo9\
	Ejemplo10\
	Ejemplo11\
	Ejemplo12\
	Ejemplo13\
	Ejemplo14\
	Ejemplo15\
	Ejemplo16


clean:
	rm ${EXES}
